### ISSUE TITLE
模拟器获取位置失败啊大佬

### ISSUE THREAD

**Issue by encryption-name** [cyanot/CphrAutoCard#1]
因为网络延时，目前还没获取到您的考勤位置
![image](https://user-images.githubusercontent.com/25360488/103508552-28b8da80-4e9c-11eb-96a9-110f09286727.png)

**Comment by cyanot** [comment]
app服务器问题吧，避开高峰期

**Comment by encryption-name** [comment]
应该不是服务器问题，我不是高峰期时也试过了，您用的什么模拟器？我用的是夜神模拟器

**Comment by cyanot** [comment]
逍遥模拟器（个人版）--使用精准定位

**Comment by encryption-name** [comment]
![image](https://user-images.githubusercontent.com/25360488/103738517-1327ea00-502f-11eb-91b6-abd2fca46f9e.png)
大佬，用了逍遥模拟器（个人版）--使用精准定位之后，上个问题小时了，但是定位出现了问题，定位修改了，app里还是取到错误的位置了

**Comment by cyanot** [comment]
那挂个手机吧
